### ISSUE TITLE
Unhandled java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by EpicPuppy613** [PGMDev/PGM#1015]
Caused by updating from 0.12 to 0.13

Unhandled java.lang.NoClassDefFoundError, caused by: Could not initialize class tc.oc.pgm.util.nms.NMSHacks

Log file:
[latest.log](https://github.com/PGMDev/PGM/files/8914574/latest.log)

**Comment by Pablete1234** [comment]
What java version are you running this server on?

**Comment by EpicPuppy613** [comment]
> What java version are you running this server on?

Java 17, but interestingly, 0.12 still works

**Comment by EpicPuppy613** [comment]
> > What java version are you running this server on?
> 
> Java 17, but interestingly, 0.12 still works

yeah java 8 fixed it
