### ISSUE TITLE
Unintended sudden disappearance of every entity when dying on modern Lunar Client instances.

### ISSUE THREAD

**Issue by bearyr** [PGMDev/PGM#1019]
I've been looking into an issue I've noticed with PGM when a player on Lunar Client dies - specific versions will make all entities invisible upon the death of the player, and the intended death title fails to show up. The issue persists across servers and requires a full client restart in order to fix the problem.

https://user-images.githubusercontent.com/80069984/177021543-22bb9bba-310e-464b-ad51-c8bf47d87688.mp4

*You can see at the beginning of the clip that there is a chest with multiple players, yet after I die and come to the same place at 0:15 the chest and the players surrounding it are gone, despite several sound cues to indicate that there are players and the chest present. I apologize in advance for the terrible clip quality, though I ensure it does its job in showing the issue.*

The issue occurs from versions 1.16.4-1.18.2 from when I tested the issue - my assumption for 1.19 is that it'd still screw the user over, though that's negligible at the moment. Lunar from 1.7-1.12 appear to be fine, as well as other clients with Optifine loaded on those problematic versions. 
*Interestingly enough, the issue is not guaranteed to occur on every single death - though it occurs on most - and I only receive these OpenGL error message whenever my Lunar client experiences the issue.*
![unknown](https://user-images.githubusercontent.com/80069984/177021553-15eeb4bb-fb72-4bfe-93c9-8d0b836c6410.png)

I'm also not sure if this issue is caused from Lunar not being able to handle the PGM death event at those specific versions or if PGM just sends a packet that ends up being invalid for those versions specifically - I've made a Lunar ticket as well due to this.
I understand that as something client-sided and exclusive under certain circumstances that the need to look into the issue may not exist, though I've reported it nonetheless as this was causing issues on Warzone on a large scale.

**Comment by calcastor** [comment]
Can you replicate this on vanilla? I doubt this is any sort of bug with PGM and simply an issue with a change in Lunar Client, so submitting the ticket to them was a good idea.

**Comment by KingOfSquares** [comment]
PGM does some packet trickery in the death process so sounds like something Lunar client can't handle. If it works on vanilla it should be fixed on Lunars end

**Comment by bearyr** [comment]
@calcastor @KingOfSquares 
It works as intended on Vanilla when I tested last; I made this issue in the hopes of finding if it even is fixable at all - that being said, good to know that this issue can be fixed given enough time. 🙂

I'll close the issue then, I see no further point in leaving this issue open now. 
I've already made the ticket on Lunar's end, just waiting for their response now.
