### ISSUE TITLE
Add filterable scoring

### ISSUE THREAD

**Issue by Cazadorian** [PGMDev/PGM#1039]
Currently with the score module you are able to define how many points are received or reduced from things such as kills and deaths. This applies globally to everyone in the match. This however does not allow flexibility for maps, especially A/D maps, to reward different amount of points for different teams. If for example you wanted to have an A/D map where one team was able to score via kills but the other was not, this would not currently be possible. Therefore being able to filter this would allow much more flexibility for these maps, and likely have uses outside A/D maps(i.e rewarding double points in a TDM for killing someone near a scorebox).

**Comment by KingOfSquares** [comment]
It could probably probably get a `filter` and a `trigger` attribute similar to current portals

**Comment by Pablete1234** [comment]
Alternative: be able to set/add score via an action, with the value of a variable. Use killreward kit with an action to score the points (and since action supports a filter, as per variables PR, it is fully filterable)

**Comment by Pablete1234** [comment]
#1220 adds score modification functionality via variables
