### ISSUE TITLE
Hotbar layout preferences concept

### ISSUE THREAD

**Issue by Meeples10** [PGMDev/PGM#105]
Given that many players tend to put certain types of items in certain hotbar slots, perhaps a settings like Hypixel uses in their Bedwars minigame could be added to allow players to set a preferred slot for certain categories of blocks. For lack of a better explanation, a chest inventory could be shown that allows players to place named items in their hotbar, such as "Building Blocks," "Food," "Primary Weapon," etc.

Maps could optionally implement this with a new XML attribute. Here is an example based on The Fenland's map XML:
```xml
<kits>
    <kit name="spawn">
        <item slot="0" enchantment="durability:1" category="primary-weapon">diamond axe</item>
        <item slot="1" enchantment="arrow infinite:1" category="ranged-weapon">bow</item>
        <item slot="2" category="pickaxe">diamond pickaxe</item>
        <item slot="4" amount="64" category="building-block">log</item>
        <item slot="5" amount="32" category="building-block">glass</item>
        <item slot="7" amount="4" category="resource">gold nugget</item>
        <item slot="8" amount="32" category="food">cooked fish</item>
        <item slot="28" category="arrow">arrow</item>
        <chestplate enchantment="protection projectile:2">iron chestplate</chestplate>
        <boots>iron boots</boots>
    </kit>
</kits>
```
If players have not set preferred slots for any items, they could be placed in the slot defined in the XML or the next available slot if the defined slot is taken.

This is only a suggestion based on my own preference and things I have heard on Stratus. It can be ignored or modified as needed.

**Comment by RuedigerLP** [comment]
Maybe swords could be the primary weapon on default and only if the primary weapon is something different eg a spade the xml tag needs to be applied. So if categories are recognized automatically that would simplfy things a lot. So players would have a gui like this ->
![Uploading 2019-12-11_22.13.14.png…]()
And then the axe would be an alias for all types of axes or the item that has the axe category applied. Most maps give two types of blocks usually one stack has more blocks, often the bigger stack is put on the primary block hot-key so i dont know if its possible to detect this automatically.

**Comment by Brottweiler** [comment]
> If players have not set preferred slots for any items,
PGM does not store any such information of any kind. There are no user settings or anything.

**Comment by Meeples10** [comment]
> PGM does not store any such information of any kind. There are no user settings or anything.

This suggestion would apply if something like OCN's `/settings` was implemented again.

**Comment by mattarnold98** [comment]
I'll work on this one, would be a nice thing to have.
