### ISSUE TITLE
Add player tracking compass item ?

### ISSUE THREAD

**Issue by lefckntea** [PGMDev/PGM#1114]
Simply a compass which points to the direction of the nearest enemy player. Right clicking could show you their name and distance in chat but there's various ways the final thing could look like.
Never seen this discussed anywhere in the pgm community before so i guess no one really needs it but it's pretty common in a lot of other gamemodes so maybe it's simply being overlooked a little. I could see this being useful on some maps like some blitz stuff or hide and seek after some time.

**Comment by Cazadorian** [comment]
This actually used to exist in PGM as part of Ghost Squadron but was limited to Ghost Squadron, and is no longer present. I've wanted it for a few blitz maps I've made to avoid people hiding and stalling down the timer instead. 

When I've discussed it with people in the past the general idea of how to implement it is to have an attribute or default behaviour for compasses that enables tracking, and being able to tie it to a filter with it pointing to the nearest player who matches that filter. In a blitz map for example, it could be set to the blitz filter and so would point to the nearest enemy with blitz enabled. In a CTW map, it could be set to track the nearest enemy player who is carrying a piece of wool. Would be good to see it implemented again properly.

**Comment by TBG1000** [comment]
I want to chip in and say that Warzone used to have a similar functionality but exclusive to Infection maps. The compass would be given in the last few minutes to all of the infected and would point towards the nearest human (not infected) player. It would be great to use it in the same way Cazadorian is describing for such maps.

**Comment by Pablete1234** [comment]
Cazadorian explained the design/implementation i proposed pretty well, but yes, it would be given via kits (similar to how grenades are given) with a special item with that functionality, potential syntax:
```xml
<kit id="...">
  <item material="compass" tracking-filter="..."/>
</kit>
```

**Comment by arcadeboss** [comment]
This would be a nice feature.   My suggestion for how it could work:

Right clicking the compass would provide the distance between the compass holder and the nearest player not on their team. 

A compass attribute could configure the granularity (1 block, 10 blocks, etc.)
