### ISSUE TITLE
Friends no longer appearing at the top of team lists

### ISSUE THREAD

**Issue by willocn** [PGMDev/PGM#1123]
Previously, players on your friend list were shown at the top of team lists. This is no longer the case.

FFA example:
![image](https://user-images.githubusercontent.com/88864994/216366685-95d1a044-542a-44bc-ae8c-3f6287384146.png)
normal teams example:
![2023-02-02_09 25 30](https://user-images.githubusercontent.com/88864994/216366795-8ff6392b-be58-4590-b7c6-806589809894.png)

**Comment by Pablete1234** [comment]
This was already reported internally, broken as part of the change from community to community-two, which did not include the patch for tablist.
Will be resolved soon.
