### ISSUE TITLE
Map vote results shown at wrong time

### ISSUE THREAD

**Issue by willocn** [PGMDev/PGM#1127]
![image](https://user-images.githubusercontent.com/88864994/216735268-5da4ce3f-c847-4d55-adad-467dc07c013b.png)
Previously, the vote results were shown at the 5 second mark. Currently, the results are shown as the map cycles.

**Comment by Pablete1234** [comment]
Works as intended, behavior has not changed, they always have resolved when the map is needed.

When that is depends on how many seconds of pre-load time are configured, which is now no longer being used.

**Comment by willocn** [comment]
Perhaps the technical reason is no longer there, but the title gets cut off by the map cycling. It makes it a bit difficult to see what map won
