### ISSUE TITLE
Tab only shows up to 4 teams (and observers)

### ISSUE THREAD

**Issue by RuedigerLP** [PGMDev/PGM#113]
I noticed this on "Ruediger's Octawool" (8-team ctw), i can provide the map for testing if needed. Also the scoreboard wont display all objectives, this was also like this in the 1.9+ versions of pgm, i dont know if its possible to compact the scoreboard content even more but it would be very neat (maybe up to 12 teams, 11 wools per team :)).

**Comment by Pablete1234** [comment]
PGM 1.9+ supported infinite teams, not just 8 (as long as they would fit), this is a feature that should be backported

**Comment by RuedigerLP** [comment]
Everything works, but tab and scoreboard are not displaying as much as they could.

**Comment by RuedigerLP** [comment]
reintroduced by https://github.com/PGMDev/PGM/pull/632 and https://github.com/PGMDev/PGM/pull/499
