### ISSUE TITLE
Velocity Actions

### ISSUE THREAD

**Issue by OhPointFive** [PGMDev/PGM#1133]
Currently, velocity can only be applied with `<apply>`s. I think it makes sense as a player-scoped action.

It would also be interesting if velocities could be applied relative to the player's yaw and optionally pitch, although I am unsure how this should be represented or how the math would work here if it were relative.

**Comment by Pablete1234** [comment]
The feature makes sense, as for relative to player you can take some inspiration for how double jump module does it (it goes towards where you look at, but a bit higher.

You could potentially have:
`<velocity x="0" y="1" z="0" forward="5">`
So forward is the users facing direction, and it adds up the 1 upwards
