### ISSUE TITLE
Shop items that cost an item with an <attribute> aren't purchasable

### ISSUE THREAD

**Issue by mitchts** [PGMDev/PGM#1167]
Take the following XML as an example.

 You first purchase the `Red Bowling Shoes` for a single emerald. These can then be traded up with 2 emeralds for the `Blue Bowling Shoes`. However, while the `<attribute ../>` modifier is present on the item you receive and the payment, PGM never registeres that you have the required payment needed to purchase the item.

Removing the `<attribute ../>` tags from the purchasable item and the payment requirement allows you to purchase the blue shoes.

```xml
<shops>
    <shop id="ball-shop" name="Bowling Ball Upgrades">
        <category id="boots" name="`rSpeed" material="leather boots">
            <item material="leather boots" color="993333" name="`rRed Bowling Shoes">
                <attribute operation="add" amount="0.1">generic.movementSpeed</attribute>
                <payment currency="emerald" price="1"/>
            </item>
            <item material="leather boots" color="334CB2" name="`rBlue Bowling Shoes">
                <attribute operation="add" amount="0.2">generic.movementSpeed</attribute>
                <payment currency="emerald" price="2"/>
                <payment price="1">
                    <item material="leather boots" color="993333" name="`rRed Bowling Shoes">
                        <attribute operation="add" amount="0.1">generic.movementSpeed</attribute>
                    </item>
                </payment>
            </item>
        </category>
    </shop>
</shops>
<shopkeepers>
    <shopkeeper name="`bAdam" shop="ball-shop">
        <point yaw="-90">-48,7,-0</point>
    </shopkeeper>
</shopkeepers>
```

The same behaviour is seen with non-armour items as well.

Using PGM v0.16-SNAPSHOT (git-7da1edd)

**Comment by Pablete1234** [comment]
This is not necessarily specific to shops, the crux of the issue is attributes get assigned a random uuid, so two items with an identical attribute will get different uuids and so will never be "the same"
