### ISSUE TITLE
`/newmaps` must be run twice to do anything

### ISSUE THREAD

**Issue by calcastor** [PGMDev/PGM#1185]
Noted by @zzuf-fer, on OCC we are finding that running `/newmaps` only once seems to have no effect on updated maps; for instance, if a map is updated in a repo with a version update, we do not see the new version in `/map map_name` unless we run the command a second time. Have not tested on local only setups which do not pull from git repositories for maps. Potentially a regression in 394ce9ba5f9f6e4046cfb26d8ea01f4243634917. 

cc @Pablete1234

**Comment by Pablete1234** [comment]
Could you test locally with and without git repos? Also could you test if includes are involved, or does this happen with any map? Same for variants, does this happen to *all* maps, regardless of if they use or are a variant?

**Comment by calcastor** [comment]
> Could you test locally with and without git repos? Also could you test if includes are involved, or does this happen with any map? Same for variants, does this happen to _all_ maps, regardless of if they use or are a variant?

The map I experienced it with uses neither includes nor variants, so it seems to happen to all maps. With local copies of maps w/o git, everything works as expected; this seems to only happen to maps that are pulled from git repos.

**Comment by zzufx** [comment]
I've noticed just now that this _only_ happens when updating already existing maps: brand new maps are correctly loaded after a single ``/newmaps``
