### ISSUE TITLE
minbuildheight

### ISSUE THREAD

**Issue by arcadeboss** [PGMDev/PGM#1190]
A corollary to maxbuildheight.

This would be a useful option to easily prevent under map building without the need to setup region and apply configuration.

**Comment by Electroid** [comment]
Generally, it's recommended to design your map so the bottom is at `y = 0`. Though, if that's not the case, it still is best to just use regions. `<maxbuildheight>` is technically "deprecated" anyway. It won't be removed, but it's better to just use a region.
