### ISSUE TITLE
<modifybowprojectile>

### ISSUE THREAD

**Issue by arcadeboss** [PGMDev/PGM#1191]
Was going to suggest improving projectile binding to bow, since the interface mechanic isn't normal bow, but it seems to already exist....

Found this in Salvo XML, but neither modifybowprojectile nor TNTPrimed is in the documentation.

Can we get this added to PGM docs?
 
```
<modifybowprojectile>
    <projectile>TNTPrimed</projectile>
</modifybowprojectile>

```

**Comment by Pablete1234** [comment]
https://pgm.dev/docs/modules/gear/projectiles#modifying-bow-projectiles

**Comment by arcadeboss** [comment]
Ah, thanks @Pablete1234.   I tried putting those terms in the search and they didn't find any matches, but I see the page is indeed there.
