### ISSUE TITLE
Spawner - Potion Effect Issues

### ISSUE THREAD

**Issue by arcadeboss** [PGMDev/PGM#1206]
1.  **Wrong Coordinates**

I have a spawner that drops a potion effect.
The coordinates are say 5.5 and 5.5:
- The spawner fire animation appears at the correct coordinates
- The dropping visual of the bottle appears at the correct coordinates
- But the actual potion "hot spot" appears at rounded coordinates, for example: 5.0 and 5.0   
You can see this generally from the attached pictures

![2023-07-15_13 21 29](https://github.com/PGMDev/PGM/assets/3164203/484cd0a0-0d63-4096-a9b9-e59492855b90)
![2023-07-15_13 21 29_2](https://github.com/PGMDev/PGM/assets/3164203/8cb846de-b572-4c16-825f-1c217a775a8b)

2.  **Finicky**

The spawners for potion effects are very finicky:
- If I set the potion effect to last for 25 seconds, the most I will ever see applied is 20 seconds
- Even standing at the "strongest" spot, the effect time will never ever go higher than 20
- The player has to be standing in a very very precise spot to even get 80% of configured effect
- If the player is standing even very slightly off the precise point the time might only go to 18 or whatever.
- It's like the effect has a function that is moderated by the player placement.  
- Why doesn't it just go to solid 25 seconds no matter where players are standing?

Thank you!

**Comment by cswhite2000** [comment]
So this is basically vanilla behavior.

If you open up a 1.8 SinglePlayer world and start throwing splash potions around you'll find that the effect always starts in the corner of blocks.

As for why the potion effect is always less, that is also vanilla behavior. Splash potions only give the full effect time if they land directly on your head, which would in SinglePlayer be throwing the potion straight up.

Essentially all PGM is doing is creating a splash potion entity at the specified interval and location, and everything after that follows vanilla behavior. So this isn't really a bug in PGM.

If you do for some reason want a uniform effect you can always apply it via a kit.

**Comment by cswhite2000** [comment]
Also technical note, the packet being sent for this internally in SportPaper `PacketPlayOutWorldEvent` takes a BlockPosition, which means that we wouldn't be able to give a floating point position regardless.

**Comment by Pablete1234** [comment]
> Also technical note, the packet being sent for this internally in SportPaper `PacketPlayOutWorldEvent` takes a BlockPosition, which means that we wouldn't be able to give a floating point position regardless.

Ill have to correct you on that one, the spawn object packet, in the protocol, sends x,y,x as fixed-point ints, that is, with 1/32 blocks of precision

**Comment by arcadeboss** [comment]
Thanks for the feedback.

I do see that vanilla MC is pushing the splash potion effect to the grid, but would we be able to take advantage of what Pablete1234 was saying with the 1/32 block precision?  (If we cannot, would be good to update the documentation with this limitation.)

Also, I didn't see any explanation for why the full 25 seconds is not given even when standing on the best spot.   I tried in vanilla MC and if I throw a 20 second splash potion on my head, I get 20 seconds.

(In case my server is slow, I tried on the mapmaker server: 22 second potion dropped directly on my head only gives 16 seconds of effect.)

**Comment by cswhite2000** [comment]
> Ill have to correct you on that one, the spawn object packet, in the protocol, sends x,y,x as fixed-point ints, that is, with 1/32 blocks of precision

You would be correct if the splash potion breaking was using the spawn object packet. However, as I said the splash potion breaking effect, is sent using the packet `PacketPlayOutWorldEvent`. And as I said this packet sends a BlockPosition. Internally this block position is encoded into a long. 

You can find more details on 1.8 block position encoding/decoding [here](https://wiki.vg/index.php?title=Data_types&oldid=7250#Position)

But essentially the decoding is:
```
val = read_unsigned_long();
x = val >> 38;
y = (val >> 26) & 0xFFF;
z = val << 38 >> 38;
```

**Comment by Pablete1234** [comment]
nvm, I thought we were talking about the position the splash potion entity was being spawned

**Comment by Pablete1234** [comment]
Given that every single thing mentioned in this PR is a vanilla defect, i'm going to simply close it, none of these are pgm bugs.

**Comment by arcadeboss** [comment]
I never got an answer on why PGM only does 70% to 80% of the potion amount.....

Maybe no one knows, but it's a bug.

**Comment by Pablete1234** [comment]
The time of the effect is also a vanilla side-effect. PGM does NOTHING about it, it purely spawns a potion entity as if you had right-click thrown it. All the code handling stuff after that, is not pgm's. Vanilla's thrown potion effect times have always been random/inconsistent, it is what it is.

**Comment by arcadeboss** [comment]
Okay, thanks.
