### ISSUE TITLE
Spawner, add Countdown

### ISSUE THREAD

**Issue by arcadeboss** [PGMDev/PGM#1209]
Add a countdown option to the spawner feature so that players can see how long until next drop.
It would display numbers in a spatial position relative to the spawner drop position, for example:

 3 [fades out],  
 2 [fades out] 
 1 [fades out and item spawns]

- countdown - Flag to show countdown or not, default false
- countdown_before - Number of seconds before drop to begin displaying the countdown
- countdown_position - Allow countdown to be positioned anywhere relative to the spawner, example above by 6 blocks.

Reasoning:

More maps are using bedwars-style store-currency spawners that are slow.  
For example contest winner Extraterrestrial has emerald delay of 20 seconds.
With longer delays it would be nice to inform players on spawner status, similar to bedwars.

**Comment by arcadeboss** [comment]
Ah, it's a duplicate:

https://github.com/PGMDev/PGM/issues/1042

**Comment by cswhite2000** [comment]
Resolving in favor of https://github.com/PGMDev/PGM/issues/1042
