### ISSUE TITLE
Sound Feature

### ISSUE THREAD

**Issue by arcadeboss** [PGMDev/PGM#1216]
Please add a PGM feature that gives game authors ability to trigger sounds for match participants.

This could be integrated with the existing "message" functionality, or as a stand-alone feature.

The sound should be selectable.   At a minimum a positive, a negative and neutral sound are needed.  But ideally many of the available sounds would be available, from these categories:
   - ambient
   - block
   - enchant
   - entity
   - event
   - item
   - ui
   - weather

Sound needs to be scoped to player, team or match.

**Comment by cswhite2000** [comment]
Here's a proposal for xml definitions for a `play-sound` action:

Action:
```xml
<play-sound sound="custom" resource="[RESOURCE LOCATION]" volume="1" pitch="1"/>
...
<play-sound resource="[RESOURCE LOCATION]" volume="0.5"/>
```
Notes:
- The `resource`, `volume`, and `pitch` attributes would match the parameters of `net.kyori.adventure.sound.Sound.sound`
- `volume` and `pitch` would default to `1`
- `sound` would default to `custom` and have options for presets. If one of the presets is used then the other parameters would be optional. Presets would be existing sounds used in pgm.

Usage with presets would be:
```xml
<play-sound sound="objective-completion"/>
<play-sound sound="warning" volume="0.8"/>
```

Other Notes:
- For scoping this would simply call `Audience.playSound(Sound)` on whichever scope this is called for.
- The sound source would be `Sound.Source.MASTER`.
- The sound action would respect the PGM sound options.

**Comment by Pablete1234** [comment]
This was already listed in #1001, regardless i've linked the two so that info is more easily found

**Comment by arcadeboss** [comment]
If the existing message command could have a flag to trigger the alert's beep or the tip's ender-chirp that alone would do a ton to cover the sound gap.

For example:
  ```
  <message text="Note that..." tip="true">
  <message alert="true"><title>Alarm!</title></message>
```

Or
```
<message text="Alarm!" sound="alert">
```

**Comment by Pablete1234** [comment]
They're different features, and are provided by different actions. You can still group them together if you want just one action to send
```xml
<action id="send-alarm">
  <message text="Alarm!"/>
  <sound preset="alert"/>
</action>
```

**Comment by arcadeboss** [comment]
Sweet, just noticed the code.

Any idea of how long until this makes it to PROD?    I would love to take advantage of the feature.
