### ISSUE TITLE
Store Item - Description vs Lore

### ISSUE THREAD

**Issue by arcadeboss** [PGMDev/PGM#1233]
Currently, the Lore for a store item is a critical feature allowing them to be explained as needed.

However the Lore interacts negatively with store-bought items during game play with stacking issues.

Proposal:  

A new item parameter called Description which would have the same appearance in the store as Lore does, however no lore would pass to purchased items.   

Alternatively, there could be a boolean parameter which allows the same control, like keeplore="false"

**Comment by Pablete1234** [comment]
You can use an item for display, while giving a kit (with an actual item with no lore) for this purpose

**Comment by arcadeboss** [comment]
Thanks for the work-around, I will look into that.

I'd rather do it with a parameter, but glad to have an option.
