### ISSUE TITLE
Staying on death screen stops TNT from destroying blocks

### ISSUE THREAD

**Issue by willocn** [PGMDev/PGM#1343]
If you are on the death screen while TNT you placed explodes, it doesn't destroy any blocks, but still does damage to entities ~~I believe that the armorstand you are riding is eating the entire explosion, since it's invulnerable.~~

I've attached a video showing the bug
https://github.com/PGMDev/PGM/assets/88864994/4ac45a04-0bcb-4476-ba91-8a821968426a

**Comment by Pablete1234** [comment]
> I believe that the armorstand you are riding is eating the entire explosion, since it's invulnerable.

That in particular is impossible as the armorstand exists only clientside

Does this happen if it's someone else's tnt? could it be that it's considered "obs tnt" since you're dead and that avoids it breaking anything?

**Comment by willocn** [comment]
- TNT placed by self - does not destroy blocks
- TNT placed by other player - destroys blocks
- "World" TNT (placed with WE) - destroys blocks

Being above the TNT is not required. I assumed it was because that was the condition I first noticed it in.
Notably, it damages entities still - is this new behavior? I feel like someone would have noticed this before
