### ISSUE TITLE
Wall mounted blocks sometimes pop off when placed by structure module

### ISSUE THREAD

**Issue by mitchts** [PGMDev/PGM#1417]
Structures that contain wall mounted blocks (only tested with ladders and signs) will sometimes have them pop off the wall when placed.

Example structure in mapdev:

![2024-10-30_21 02 23](https://github.com/user-attachments/assets/1de74841-2a0d-4dc3-a7b7-8964d5a0c59e)

Upon cycling to the map there are already items on the ground (note that these will drop regardless of whether the item is on item remove):

![2024-10-30_21 02 10](https://github.com/user-attachments/assets/f2d17116-2755-4c27-b053-aa0c6f40b26b)

When the structure is placed:

![2024-10-30_21 01 57](https://github.com/user-attachments/assets/29f45c48-81dd-4902-a433-61de702426e3)

The ones which pop off appear to be consistent between matches. Once placed more dropped items are created in addition to the ones already dropped on match cycle.

Demo map: [ladder_struct_demo.zip](https://github.com/user-attachments/files/17570168/ladder_struct_demo.zip)

**Comment by Pablete1234** [comment]
Using `update="false"` in the `<dynamic>` should fix this
See #1419
