### ISSUE TITLE
Map Author Ranks

### ISSUE THREAD

**Issue by Xerocoles** [PGMDev/PGM#152]
Sorry if this doesn't go here, I was told like a week ago that it's most likely a PGM bug, but it used to be that when a map made by yourself is playing, you get a blue asterisk beside your name, and you get donator perms.  That would be excellent to have back.

**Comment by Brottweiler** [comment]
Pretty sure this is a thing already?

**Comment by Xerocoles** [comment]
> Pretty sure this is a thing already?

Idk but it doesn't work on Stratus at least

**Comment by KingOfSquares** [comment]
Anyone know what this was called in ProjectAres?

**Comment by Pugzy** [comment]
Its referenced as `MAPMAKER` in a few areas.
