### ISSUE TITLE
Cannot edit rotation while server is running

### ISSUE THREAD

**Issue by Brottweiler** [PGMDev/PGM#158]
If you try edit the rotation when the server is running, it will dismiss your changes on the next cycle.

**Comment by Pablete1234** [comment]
This issue is caused by rotations saving the rotations file after every map cycle, to save the next map

**Comment by Electroid** [comment]
Still an issue?

**Comment by TheMolkaPL** [comment]
> Still an issue?

Yes, should be using SQLite for this, probably.

https://github.com/Electroid/PGM/blob/6aee67bffac1b54a30f14f6a795b6901d19143f2/src/main/java/tc/oc/pgm/rotation/MapPoolManager.java#L28

https://github.com/Electroid/PGM/blob/6aee67bffac1b54a30f14f6a795b6901d19143f2/src/main/java/tc/oc/pgm/rotation/MapPoolManager.java#L62-L68

**Comment by Pablete1234** [comment]
Either SQLite, or just using a different yml file to save rotation data vs rotation config. Would also be good to store map scores for voted pools.

**Comment by Brottweiler** [comment]
This was fixed.
