### ISSUE TITLE
Core leak distance info

### ISSUE THREAD

**Issue by Xerocoles** [PGMDev/PGM#196]
I think it would be really helpful, if, instead of just "You damaged Blue's Core." if it could say "You damaged Blue's Core.  You need to leak the lava four blocks down."  Or just _something_ like that, because it's very very unclear to public players as to how leaking cores exactly works, and since it varies per map it's annoying.

**Comment by Pablete1234** [comment]
By that rule: "You touched the wool, now you must return it back to your spawn" ? 

I am not sure that the touch message should be the one informing about how to complete an objective. That's a message you get when you're on a tense situation on the enemy base, you are not going to be reading what chat tells you before getting killed, most of the time

**Comment by Electroid** [comment]
How about we add core leak distance to proximity tracking? That's something we always wanted to do for tournaments but never got around to it.

**Comment by Pablete1234** [comment]
@Electroid That's basically what the title looked like, but then the request just is like a completely different thing.
Core leak proximity would be great, but proximity isn't shown in public matches so i don't think it's really related to this issue.

**Comment by Pugzy** [comment]
I had a play with Core proximity in the past but the way it should be displayed is a little confusing.
We are dealing with numbers that decrease in size to a goal where the upper bound can vary (if you leak from the top of the core you have more blocks for it to travel). This means a percentage style system wouldn't work unless you counted the very top or middle point of the lava to be the total.

**Comment by Xerocoles** [comment]
I mean, arguably it could make sense to say you picked up the wool, bring it back to spawn.  I wouldn’t mind as long as you narrow the words down.  But it’s more of a thing in DTC because it’s always a different number of how far you need it to go, and it’s something that’s nice for even a veteran at the game to know, not just new players.  Because otherwise you just never know how far you’re trying to leak it, which is how you actually _win_ the game

**Comment by RuedigerLP** [comment]
maybe /map should have the leak distance information,

also for cores maybe an option for a horizontal leak distance, well actually more like a spereical leak distance could be nice

**Comment by Xerocoles** [comment]
Spherical might be cool, though also maybe just adding to the confusion.  Adding in /map isn’t worth it.  People aren’t gonna be checking that for core leak distance, especially not when they’re at the core mining it.

**Comment by Pablete1234** [comment]
Core leak distance should be just a number of how many blocks remain, it's a proximity status, if you start from the top it may be 8, if you start from the bottom it may be 4. 
If it gets to 0 it means you won.

About spherical distance, i don't see that as helping the playability at all

**Comment by RuedigerLP** [comment]
well its a different gameplay if u can leak the core to the side as well

**Comment by rafibaum** [comment]
This will be developed with the tournament module.

**Comment by Pablete1234** [comment]
What does a tournament module have to do with PGM? IMO tourrnament "mode" should just be a set of config values, like, enabling proximity.
This isn't necessarily a feature for specifically tournaments, rather, should just be what "proximity" means for a core

**Comment by rafibaum** [comment]
I meant that solely in the context of "when this issue will become prioritised".

**Comment by TiTo418** [comment]
#581 fixes this
