### ISSUE TITLE
Kits don't give items if no items have defined slots

### ISSUE THREAD

**Issue by RuedigerLP** [PGMDev/PGM#212]
^

**Comment by Pablete1234** [comment]
Care to elaborate? What did you test? All maps with non-defined slots in kits give no items at all?

**Comment by RuedigerLP** [comment]
ok so after futher testing i noted that, if none of the items in a kit has a desiganted slot the items just dont appear, but once only one item has a slot everything works again, i also noticed that it only applies to items e.g. potion effects work all the time
