### ISSUE TITLE
Add a chest GUI for player settings

### ISSUE THREAD

**Issue by Meeples10** [PGMDev/PGM#217]
This could help players see what settings are available and allow them to easily change settings by clicking, rather than typing commands.

**Comment by KingOfSquares** [comment]
Im thinking of the following implementation:

- Make a new MatchModule `SettingsGuiMatchModule` or some other name

- Have a method listen for a InventoryClickEvent on a specific item while in obs (Maybe a sheet of paper)

- When the item is clicked, create a new GUI with `Bukkit#createInventory` with items representing each setting, open that GUI with `event#getPlayer#openInventory` and on each item hover it should display what setting it is and if it is SHOWN or HIDDEN/ ACTIVATED or NOT ACTIVE and so on

- The method will check the players settings with `getSettings` to decide which values it will put in the lore of each item in the GUI.

- Have another method listening for a InventoryClickEvent on each item in the GUI and then toggle that setting by sending a /toggle <clicked setting>.

- Unsure if all items in the GUI should be the same item to limit which types of InventoryClickEvent we need to listen for, or if each setting should have their own item that corresponds to the type of setting it represents (Sounds -> Noteblock etc..)

Maybe kinda messy? Hope you get my thoughts. I will wait making this until somebody can tell me if it's the right way to go hehe.

**Comment by Pablete1234** [comment]
@KingOfSquares Look at the current implementation of observer tools. Some of the tools there (like obs visibility) are literally changing a setting.

The idea is, this should be a menu with all relevant settings

**Comment by KingOfSquares** [comment]
This, as in the pre-existing observer tools? Do we just expand on that? Or make a new GUI for all settings, i don't understand.

**Comment by Pablete1234** [comment]
Observer tools can be used as reference on how you could implement the gui. it would be a different menu

**Comment by Brottweiler** [comment]
Not sure if this is related or should be in it's own issue, but a GUI for reporting would be nice as well. Most servers today don't allow you to write your own report message. Having a GUI would totally remove joke reports too, but the false reports would not go down.

You would just type `/report <player>` and a GUI will show up. You configure in the config what block or item should show and what the reason would be. So a diamond sword could be hacking. A TNT block would be team griefing etc.

**Comment by rafibaum** [comment]
Added in #451

**Comment by Pablete1234** [comment]
closed by #916
