### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by Electroid** [PGMDev/PGM#219]
While refactoring in #218 I've noticed several things that will likely make PGM more performant.

- [ ] We are copying `Collection`s too much (`ImmutableX`)
- [ ] Consider using [`fastutil.di.unimi.it`](http://fastutil.di.unimi.it)
- [x] `MatchModule`s need to be cleaned up on `#unload()`, most are not right now
- [x] Async sidebar (possible) and tablist (maybe possible)

**Comment by Pablete1234** [comment]
Pretty sure these are not relevant anymore, given how much time i've spent profiling performance issues on pgm, the remaining 2 listed are never showing up as relevant
