### ISSUE TITLE
Replace attribute for items

### ISSUE THREAD

**Issue by RuedigerLP** [PGMDev/PGM#234]
so i think it would be rly neat if u could define what item the item in a kit should replace in the players inventory, that will be useful e.g. if u apply a special kit in the woolroom region u could specify what items u want to upgrade, also if the item that should be replaced is not found the item should just get applied normally
`
<kit>
    <item material="diamond sword" replace="iron sword"/>
</kit>
`

**Comment by KingOfSquares** [comment]
This would only apply if the player has the item that is going to be replaced? Or would it give the items regardless?

**Comment by RuedigerLP** [comment]
I think it should give the item regardless.

**Comment by RuedigerLP** [comment]
https://github.com/PGMDev/PGM/pull/1061
