### ISSUE TITLE
Add support back to give, take, and lend kits 

### ISSUE THREAD

**Issue by CrazyisCreeps** [PGMDev/PGM#236]
Unless I'm mistaken, the ability to do so was only introduced in a proto past 1.4.0, thus does not work in this version of PGM. With this, you were able to dynamically apply & remove kits, without the restriction of needing to enter a region in order to receive the kit.

For reference, here's the documentation page that has some (limited) info on this http://docs.oc.tc/modules/kits

**Comment by KingOfSquares** [comment]
Fixed in #932
