### ISSUE TITLE
AFK timer

### ISSUE THREAD

**Issue by Brottweiler** [PGMDev/PGM#241]
Move AFK players to observers after X minutes.

**Edit:** Also, make AFK observers show up in italics in the player list.

**Comment by Electroid** [comment]
OCN disabled it years ago because it was generating weird false positives. But should look at re-introducing it.

**Comment by KingOfSquares** [comment]
How many minutes do we think is appropriate before marking a player as AFK? 5 minutes? 3 minutes? Do we make it a config option?

**Comment by Brottweiler** [comment]
5 or 10 minutes. 3 is very short, you should probably be able to take a bathroom break or get a cup of tea without getting kicked. 

I don't see why this would not be configurable. 10 minutes could be default maybe?

**Comment by KingOfSquares** [comment]
Ok so i'm thinking of how this would be implemented, here are my thoughts:

Option 1:
something like this: https://pastebin.com/JEtVvv7K

Option 2:
something like this: https://pastebin.com/Y2sGqRbJ

So i'm just not sure what part of playing should be tracked without affecting the server performance.

**Comment by Pablete1234** [comment]
Out of scope for PGM

See https://github.com/OvercastCommunity/Idly for an implementation of this feature
