### ISSUE TITLE
Mercy rules for score module

### ISSUE THREAD

**Issue by Xerocoles** [PGMDev/PGM#250]
This would basically be a thing in xml that ends games when a certain team is up by enough points.  If it's a CTF with timelimit but no flag max, then you could set it to be like `mercy rule="5"` within the flags module, and if a team is leading 5-0, or 6-1, etc, then the match ends.  Each map would pick its own number, due to some being more high-scoring than others.  This was either already implemented in OA or about to be, but it would be very useful in competitive blowouts where nobody even tries at a certain point.

**Comment by RuedigerLP** [comment]
it hink it would be an attribute for the score module

**Comment by Pablete1234** [comment]
Yes, this, if implemented, i think should definetly be part of the score module.

May need to consider if percentage-based makes sense, would you want it to just end the match if one team is having, for example, 3 times as many points as the other? 
This obviously wouldn't make sense for the match start cause 0 to 3 could be recoverable but 10 to 30 is alot harder, if percentage-based was added, it probably would need to be in combination with some minimum, but it may not be worth the trouble.

**Comment by Xerocoles** [comment]
> Yes, this, if implemented, i think should definetly be part of the score module.
> 
> May need to consider if percentage-based makes sense, would you want it to just end the match if one team is having, for example, 3 times as many points as the other?
> This obviously wouldn't make sense for the match start cause 0 to 3 could be recoverable but 10 to 30 is alot harder, if percentage-based was added, it probably would need to be in combination with some minimum, but it may not be worth the trouble.

yeah sorry score module

No i dont think we want percentages, I fail to see why that is better in any way, considering each map can customize the number.  Also, when playing a match, it should be easy to tell how many to need to be up by, rather than doing some math like wait ok we need 2 more, unless they get one, and then we need 4, and - ya know, just, over-complicated for the sake of what?  I get that it could help sort out if a certain match is playing really high or low scoring, but most competitive matches per map won't vary too much, so i think it's too confusing in-game to be worth it.  Does that make sense?

**Comment by Xerocoles** [comment]
@Pugzy sup mate wanna do this? 💞

**Comment by Pugzy** [comment]
Hacked this together on https://github.com/Pugzy/PGM/tree/mercy-score-rules which seems to work. 

Went for the option to set a `mercy` value in the XML which also optionally respects a predefined `limit`. If a team leads by the `mercy` amount they will win, otherwise its first to the score `limit`. As an added bonus this figure is set within the score limit so it means the scoreboard is updated too!

I've run into the problem where I'm sorting team scores every time the limit is checked, which doesn't seem very efficient, going to try and rework it so it uses the score change event and tracks the second-highest competitor that way.

Open to advise on how to improve this as I think it has potential.

**Comment by rafibaum** [comment]
This smells like a micro-optimisation to me. Most maps will have 2 teams (maybe 8 if you're Ruediger). Sorting 8 teams isn't that bad. If you want something O(n) you can manually go through the list and pick out the top two teams. Otherwise something like you suggested would work.

**Comment by Pablete1234** [comment]
@rafibaum My tablist-testing-32-team-map is crying out of irrelevance right now.
