### ISSUE TITLE
Mark objectives with flag particles

### ISSUE THREAD

**Issue by VladyslavLukyanenko** [PGMDev/PGM#264]
Mark objectives with the flag line on it, on the objectives so people know where they at and make it toggleable in settings

**Comment by Pablete1234** [comment]
Could just extract the particle beam for flags and make it re-usable for different objectives (with less particles per second and probs less height)? (beam on/off always xml-based)

**Comment by VladyslavLukyanenko** [comment]
Wouldnt it be better per player basis, so people can toggle if they dont need that?

**Comment by RuedigerLP** [comment]
also maybe for wools the beam could change from the woolpickup location to the wool monument once u picked up the wool

**Comment by Pablete1234** [comment]
@VladyslavLukyanenko 1.9+ PGM had a toggle for particles i'm pretty sure. Regardless, it's the xml that should say beam="true" (and then the individual user is able to ignore it either way)

**Comment by Pablete1234** [comment]
Superceeded by #899
