### ISSUE TITLE
Improve spectator mode

### ISSUE THREAD

**Issue by Pablete1234** [PGMDev/PGM#294]
When you spectate a specific player in spectator mode, and that player dies, your camera justs gets stuck there until you shift-out and re-join.

It would be nice of PGM could keep track of who you spectate to prevent you being unmounted, two ways to implement this would be:
 - Don't make that player invisible while you spectate him (so after respawning you're just teleported and it works)
 - Just sends the camera packet to the player spectating after the player respawns.

I personally think the second one is a better option, the first one seems a bit of a hack.

**Comment by EricZeiberg** [comment]
POV spectating is a vanilla feature, so it would be difficult to modify in PGM, as far as I know. Could do something with SportPaper maybe.

**Comment by Pablete1234** [comment]
You send a packet to the server to start spectating an entity. The server (or pgm) can pick-up on it and act accordingly

**Comment by Pablete1234** [comment]
#840

**Comment by KingOfSquares** [comment]
@Pablete1234 since #840 is merged this can be closed?
