### ISSUE TITLE
Switch to Paperclip-based Bukkit distribution

### ISSUE THREAD

**Issue by rafibaum** [PGMDev/PGM#30]
Very minor issue, but right now the current recommendation involves directly downloading a Bukkit jar from a privately hosted location. For well-known reasons this is inadvisable as distribution in this fashion violates the GPL license under which Bukkit was created. Paper has created a really easy deployment mechanism called [Paperclip](https://github.com/PaperMC/Paperclip) and it's super easy to use it to create clean jars. It even has a [Maven plugin](https://github.com/PaperMC/PaperclipMavenPlugin) so you can automate the whole process.

**Comment by Electroid** [comment]
Yea, thanks for pointing this out, we'll have to take a look.

**Comment by chatasma** [comment]
https://github.com/Electroid/SportPaper/pull/52 should resolve this

**Comment by AustinLMayes** [comment]
SportBukkit now produces a Paperclip release
