### ISSUE TITLE
Document custom patches required

### ISSUE THREAD

**Issue by Electroid** [PGMDev/PGM#32]
Eventually, it would be nice if `PGM` could run on different `Bukkit` implementations / flavors. In order to determine the feasibility of that, someone should put a document together of all the APIs and server patches for `PGM` to work at runtime.

**Comment by cswhite2000** [comment]
Well this isn't exactly that but this is a list of most of things that PGM uses that are in sportpaper 1.8, but not spigot 1.8:

Events:

- [ ] PlayerInitialSpawnEvent
	- Possible Replacement: PlayerLoginEvent, PlayerSpawnLocationEvent
- [ ] PlayerSkinPartsChangeEvent
	- no replacement possible, we don't really need to support this
- [ ] PotionEffectRemoveEvent:
	- no practical replacement without repeatedly checking if the player still has the potion effect
	- used in shield modules
- [ ] PlayerAttackEntityEvent:
	- :shrug:
- [ ] PlayerLocaleChangeEvent:
	- check locale of player each time
- [ ] PlayerOnGroundEvent:
	- used in fall tracker, and SpleefTracker
	- no good replacement:
- [ ] EntityExtinguishEvent:
	- used in fire tracker
	- no good replacement
- [ ] BlockDispenseEntityEvent:
	- used in OwnedMobTracker
- [ ] PlayerSpawnEntityEvent
	- used in OwnedMobTracker
- [ ] BlockFallEvent:
	- used in AnvilTracker:
- [ ] ExplosionPrimeByEntityEvent
	- Not really a good replacement for this
		- Might have to just look at interactions for what would cause an explosion prime event in the first place
- [ ] EntityDespawnInVoidEvent:
	- Entity death event isn't called for fallingblocks, used in block drops module
	- module should still work without this
- [ ] InventoryClickedEvent:
	- rely only on InventoryClickEvent
- [ ] Physical interface
	- Check if an event has a getworld method manually
- [ ] EntityAction
	- Used where events have a specific actor entity
	- used in Causefilter, a bit of a pain to get this behaviour without the api
		- have to check the specific event to see if it has this information,
			- some events lose this information without the api
- [ ] PlayerActionBase


Api changes:

- [ ] Player.showTitle():
	- send packets or use ProtocolLib
- [ ] Bukkit.allocateEntityId();
	- use reflection
- [x] PersonalizedComponent
	- Move class to intake
- [ ] Skin api
	- Move api to pgm
- [ ] CraftTeam is private, but only used to call a method with no side effects
	- Copy method to PGM
- [ ] Attribute API
	- This is a bit of a pain to do with reflection
	- added in 1.9, sportpaper api is mostly just 1.9's api copied to 1.8
		- some added features though with canDestroy and canPlaceOn, which would be tedious to replicate
- [ ] ImmutableMaterialSet
	- Move to PGM maybe


Packets:

Private fields for PacketPlayOutScoreboardTeam
	- use reflection or protocolLib
PacketPlayOutPlayerInfo.PlayerInfoData added constructor and modified displayname field
	- use reflection or protocolLib
Private fields for PacketPlayOutPlayerInfo
	- use reflection or protocolLib
PacketPlayOutSpawnEntity added constructor
	- use reflection or protocolLib
PacketPlayOutNamedEntitySpawn added constructor
	- use reflection or protocolLib
PacketPlayOutSpawnEntityLiving added constructor
	- use reflection or protocolLib
Private fields in PacketPlayOutEntityMetadata
	- use reflection or protocolLib

**Comment by Pablete1234** [comment]
What i'm seeing is, some of those do have APIs in newer bukkit/spigot versions. Would be nice if their uses could be abstracted to require sportpaper for them to work on 1.8, but be able to work with native paper spigot for newer versions (like 1.15).

**Comment by GBroad** [comment]
@cswhite2000 PotionEffectRemoveEvent now has a spigot counterpart:

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityPotionEffectEvent.html

**Comment by Electroid** [comment]
Done with Spigot 1.8 support.

**Comment by GBroad** [comment]
> 
> 
> Done with Spigot 1.8 support.

As far as other versions above 1.8, is this planned at all?

**Comment by Electroid** [comment]
> > Done with Spigot 1.8 support.
> 
> As far as other versions above 1.8, is this planned at all?

Yes, the goal is for 1.16 support as well. Follow #852
