### ISSUE TITLE
Re-add Lootables

### ISSUE THREAD

**Issue by qlados** [PGMDev/PGM#358]
This feature was introduced when Lifeboat was a thing to allow the creation of Survival Games/Skywars maps. However I think that it has utility beyond those gamemodes and should be reintroduced to the plugin at some point.

Reference: http://docs.oc.tc/modules/lootables

**Comment by Pablete1234** [comment]
This is still a missing feature that should eventually come back

**Comment by KingOfSquares** [comment]
This can be closed(lets go)
#1044
