### ISSUE TITLE
Negative Points

### ISSUE THREAD

**Issue by RuedigerLP** [PGMDev/PGM#361]
Negative points dont work with all point souces, they work with scoreboxes or the score module, but hills and flags just ignore it and do nothing.

**Comment by rafibaum** [comment]
What should they do in that situation?

**Comment by Pablete1234** [comment]
If your xml defines a hill/controlpoint, or flag, that awards negative points per second, you should be given negative points. Currently your score is just not incremented nor decremented

**Comment by RuedigerLP** [comment]
https://github.com/PGMDev/PGM/pull/869
