### ISSUE TITLE
Filters and show attribute for Blitz module

### ISSUE THREAD

**Issue by RuedigerLP** [PGMDev/PGM#365]
show="false" would just hide the blitz configuration from the scoreboard,
and filters would allow games like bedwars or more project ares oriented variants with the bedwars machanics to work with less hacky stuff

**Comment by rafibaum** [comment]
What sort of filters are you thinking of?

**Comment by RuedigerLP** [comment]
I want to set a team to blitz once an objective is completed, so id say team and objective filters.

**Comment by Pablete1234** [comment]
I'm assuming a filter for when lives should decrease should be good for this. Gives enough flexibility to do things like dying on your own base means not losing lives, etc.
