### ISSUE TITLE
Block placements play sound in regions with restrictions

### ISSUE THREAD

**Issue by CrazyisCreeps** [PGMDev/PGM#407]
If you place an anvil in a region where you aren't supposed to place blocks, for example most spawn regions, the sound of placing the block will play even though the block isn't being placed.

If you do this with an anvil you can basically spam the annoying anvil sound to everyone within the nearby range to hear it. It gets annoying fast basically.

If it's possible to patch within the plugin it would be greatly appreciated. If it can't be, let me know.

**Comment by Meeples10** [comment]
After some testing, it seems that this happens with all blocks, not just anvils.

**Comment by Electroid** [comment]
Not sure if we can fix this, but we can look into it.

**Comment by EricZeiberg** [comment]
Might be a SportPaper issue

**Comment by Pugzy** [comment]
Looks to be fixed in [this CraftBukkit patch](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/121dfc098a882c8fb157e8232001ce19c9846ccf) in response to [this jira issue](https://hub.spigotmc.org/jira/browse/SPIGOT-1288).

**Comment by AustinLMayes** [comment]
Fixed in https://github.com/Electroid/SportPaper/commit/9203b9c39e0e45f272678d88db7b3000e7e89b91
