### ISSUE TITLE
Block regen module sometimes regens parts of the previous map

### ISSUE THREAD

**Issue by Brottweiler** [PGMDev/PGM#408]
Image as example 
![image](https://user-images.githubusercontent.com/1613137/79641855-4ae9bb80-819a-11ea-995b-3757b8f1c52e.png)

**Comment by EricZeiberg** [comment]
Difficult to reproduce. Do you happen to know what map was played before this?

**Comment by Brottweiler** [comment]
Probably Medieval Warfare, but it has also happened with Sand Wars.

**Comment by KingOfSquares** [comment]
I have a way to reproduce this now, gonna work out a fix and do a write-up ASAP
