### ISSUE TITLE
There is no team size limit before match start

### ISSUE THREAD

**Issue by KingOfSquares** [PGMDev/PGM#417]
PGM does not prevent teams from being overfilled before a match has started. This means that all players (not just premium) can join full teams if it is before the match has started.

To reproduce in singleplayer: set team sizes to 0 and /join on an account without permissions.

**Comment by rafibaum** [comment]
Do they let you go beyond team capacity past the defined overfill?

**Comment by Pablete1234** [comment]
Yes, you can join seamingly infinite players before match start no matter map size, they do seem to balance based on team sizes (if one team is 10 times bigger, it assigns 10 times as many players)
