### ISSUE TITLE
Sidebar does not sort by scores in FFA

### ISSUE THREAD

**Issue by KingOfSquares** [PGMDev/PGM#422]
Maps using the party type tributes instead of teams would be all FFA maps and probably alot of Arcade maps. (Not sure if intended behavior on rage maps with teams?)

I believe the current logic in place for ordering is just the order players joined.

The ideal logic would be listing the players with the highest score on top and lower scores below in decreasing order.

How it looks ATM
![2020-04-22_00 36 51](https://user-images.githubusercontent.com/19822231/79917770-746d4600-842b-11ea-8a65-26248dc1329b.png)

**Comment by Pablete1234** [comment]
"Maps that uses Tributes", tribute is an internal name, it's just ffa (free-for-all)

**Comment by Pugzy** [comment]
Should team in other score based gamemodes not also be ordered by score?

**Comment by Pablete1234** [comment]
IMO, the most sensible way to implement it, is to have your own competitor always appear on top, and after that, all others sorted. This means for both teams and ffa. Including objective-based maps (like ctw or dtc) where observers should see the teams sorted by who has the most wools/touches etc (the win conditions).

**Comment by Diamyx** [comment]
<img src="https://i.imgur.com/k296C0v.png">

seems to work on Frontier

**Comment by Pablete1234** [comment]
#586 Fixes some of the things discussed here, i'm not sure that the issue itself can still happen in current pgm
