### ISSUE TITLE
Custom villager trades

### ISSUE THREAD

**Issue by RuedigerLP** [PGMDev/PGM#463]
Vanilla villager shops get crowded once you have more then a few items and updating villagers over version-changes and map updates can be a pain. To provide a better overview of the shop items i'd suggest that a shop is divided into sub-shops that are displayed in an inventory with items as icons (like with the classes module), those sub-shops would then open a regular villager shop with the trades. Maybe every mob (maybe even every entity, would be funny if ur team mates are a shop xD) could be used as a shop and shops could be controlled by filters.

What would also be cool is if u could spawn in a shop with a spawn-egg, that would be useful, you could sell better shops or take your shop a strategic position.

Maybe it could work like this you spawn the mobs that are the shops with the spawner module and then with something like and entity-mods module one could add shops to a certain kind of entity.

**Comment by Pablete1234** [comment]
IMO making arbitrary trade entities may not be the best, using villagers is pretty common in minecraft for "place to trade". It would be interesting to define the trades in XML instead of in-game, but i don't think much more than that should be done
