### ISSUE TITLE
Issues on scoreboard rendering compact wools

### ISSUE THREAD

**Issue by Pablete1234** [PGMDev/PGM#509]
![image](https://user-images.githubusercontent.com/11789291/83049347-4e9b1880-a04b-11ea-97f5-261fec270e44.png)

In this map, the scoreboard should be using the "highly compact" mode, where it removes lines between teams, to be able to fit the last team, also, there seems to be a single space between each wool in the same row, this should be 2 spaces because it's only displaying 3 wools so it can fit

**Comment by alexsosnovsky** [comment]
I'm aware of this. Will look into it today or tomorrow.

**Comment by Shrman007658** [comment]
Hey! I am new to open source and would love to tackle this issue. Can you walk me through? Cheers!

**Comment by KingOfSquares** [comment]
> Hey! I am new to open source and would love to tackle this issue. Can you walk me through? Cheers!

Hey Sherman! It seems this issue already gotten a submitted fix over at #510 
If you search trough the "good first issue" tag maybe you can find something else to work on?

I also recommend joining the Discord we use if you have not already [(inviteLink)],(https://discord.gg/CvJGbrV) look for #contributing and #debug if you want to talk to us about how to contribute/if you need help with the codebase!
We can also help you choosing a good first issue if you are not sure where to start.

**Comment by Shrman007658** [comment]
No problem at all! :) I will be joining the discord soon!
