### ISSUE TITLE
/timelimit doesn't automatically set a victory condition

### ISSUE THREAD

**Issue by Diamyx** [PGMDev/PGM#529]
I remember this being a thing on OCN, but basically when you set a timelimit it should take into account the existing win condition (e.g. players remaining on a blitz map)

**Comment by EricZeiberg** [comment]
Wasn't this fixed by #410? Or is this a different issue?

**Comment by Pugzy** [comment]
> Wasn't this fixed by #410? Or is this a different issue?

That issue fixed a different bug. The one described in the OP is due to a recent command refactor. If you don't provide a victory condition it defaults to a tie rather than taking into account any existing conditions.
