### ISSUE TITLE
Allow respawn module to be filtered

### ISSUE THREAD

**Issue by CrazyisCreeps** [PGMDev/PGM#533]
It would be really handy to be able to throw a filter onto the respawn module, in order to dynamically trigger it at different points during a match. For example being able to trigger different respawn times like the following:

![image](https://user-images.githubusercontent.com/7937351/84425163-1e2cb000-abef-11ea-9647-97dd94467625.png)

**Comment by Pablete1234** [comment]
This was added in 1.9+ pgm, should be backported

**Comment by qlados** [comment]
#246 is the same issue and was posted months ago
