### ISSUE TITLE
Renaming teams does not update team chat prefix

### ISSUE THREAD

**Issue by Pablete1234** [PGMDev/PGM#534]
After a team is aliased as something else, talking in chat still uses the old prefix, like `(Red)` instead of `(New name)`

**Comment by EricZeiberg** [comment]
Are you sure? I am unable to reproduce this issue. 

![](https://puu.sh/FVtoU/e5cf073d11.png)

**Comment by Pugzy** [comment]
Try joining typing in team chat then changing the team name. The chat prefix doesn't seem to be updated once initially created.

Pablo suggested that the channel may not be created and prefixed until used.
