### ISSUE TITLE
Make PGM independent from SportPaper

### ISSUE THREAD

**Issue by Electroid** [PGMDev/PGM#54]
Most of the custom `SportPaper` patches are either not necessary, or are also supported by `Spigot`. Ideally, `PGM` should be able to run on any, reasonable, version of `Bukkit`. Some reflection will be required, especially for `NMSHacks`, but I think that's okay.

If we can, it would also be nice if PGM could run on later versions of `Bukkit` as well, but we'll have to see if that's feasible.

**Comment by AustinLMayes** [comment]
This won't work without a lot of boilerplate since SP adds a lot of events that PGM listens to
