### ISSUE TITLE
Overtime

### ISSUE THREAD

**Issue by qlados** [PGMDev/PGM#547]
Introduce a new (optional) child element of the score module called overtime:
```
<score>
    <overtime/>
</score>
```
If the time runs out while the score is tied, overtime activates. It is announced in the chat and also displayed in the bossbar. Overtime ends whenever the tie is broken (one team gets a higher score than the other team), ending the match regularly with the winning condition specified in the time module.

**Comment by KingOfSquares** [comment]
ref: https://github.com/PGMDev/PGM/issues/473#issuecomment-626084693

**Comment by Pablete1234** [comment]
Should not be part of score module. Overtime should be generic for all gamemodes
