### ISSUE TITLE
Match players getting teleported to default world

### ISSUE THREAD

**Issue by Pugzy** [PGMDev/PGM#560]
### Issue

Players are teleported to the default world generated by the server after a few seconds of the match starting.
Players keep the spawn kit and can still the feed from the match including chat and scoreboard.

The player is unable to run commands such as speaking in chat as they're not a match player.

![image](https://user-images.githubusercontent.com/8608892/87221785-a5904f00-c366-11ea-92a0-62fcf0f951fa.png)

Killing yourself, relogging, and the match cycling will resolve the issue putting you back into the main game world.

The only culprit I can think of is the pre-loading of worlds and gradual teleportation feature.
OCC config options below, not sure if this is config specific or just appears more often due to match frequency.

OCC Config values
```yaml
experiments:
  match-preload-seconds: 5
  match-destroy-seconds: 15
  match-teleports-per-second: 10
  tab-render-seconds: 1
  unload-non-match-worlds: true
```

### Examples:
Instances, where this has occurred, have been in the first few seconds of the match starting.

#### Streamline II
around 10 seconds into the match
https://youtu.be/Y8Llpz8hgqE

#### Limbo 2
about 5 seconds in to the match (no hills captured yet) user also reports that 
> a few matches after I stayed in the old map as well instead of cycling with everyone.

![image](https://user-images.githubusercontent.com/8608892/87221609-36662b00-c365-11ea-8111-590fb4a0a21a.png)

#### BalloonsDTM
at the start of the match (screenshot taken at 15 seconds)
![image](https://user-images.githubusercontent.com/8608892/87221804-c658a480-c366-11ea-9d9f-cafbb1b5e9dd.png)

#### Desert Cataract
3-4 seconds after the match has started
https://discordapp.com/channels/86514356862320640/86514356862320640/720516608191103008

**Comment by CoWinkKeyDinkInc** [comment]
I can confirm this has happened to me once before when I was in the middle of a match of Water Drop
![2020-07-07_22 11 05](https://user-images.githubusercontent.com/7586568/87233547-c320e100-c385-11ea-9a44-3a2046ab6fd4.png)

**Comment by Pugzy** [comment]
I've not seen anyone complain about this one in a long time. I can only assume this was 'fixed' somewhere along the line.

Will close unless anyone knows anything I do not.

**Comment by Pablete1234** [comment]
I'd place my bets on cc520ae being the fix. 685c73c was also loosely related but not quite the same
