### ISSUE TITLE
Add a isPresent/ifPresent to needModule

### ISSUE THREAD

**Issue by KingOfSquares** [PGMDev/PGM#568]
Currently every user of `incrementScore` (Controlpoints, Flags, Payload in the future?) does similar logic on point incrementing.

Something like
```java
ScoreMatchModule smm = match.needModule(ScoreMatchModule.class);
if(smm != null) smm.incrementScore(score);
```

I believe this can be abstracted out into a `match.incrementScore` or something similar.

**Comment by Pablete1234** [comment]
If match has no scoring, this wouldn't make any sense. Maybe instead:
`match.optionalModule(ScoreMatchModule.class).ifPresent(smm -> smm.incrementScore(score));` ?

**Comment by KingOfSquares** [comment]
That makes sense, `optionalModule` should be implemented at a lower level for all modules that does not get loaded on every match by default. Because now that I think about it the check
```java
MatchModule mm = match.needModule(SomeMatchModule.class);
if( mm != null ) {. . .}
```
is done on more than just the `ScoreMatchModule` right..

**Comment by KingOfSquares** [comment]
So my thought after some thinking is that `needModule` should just get a `ifPresent/isPresent` integrated.

**Comment by Electroid** [comment]
A long time ago, when the "framers of PGM" were designing modules, they decided that `Match` would not contain any logic (even for essential features like scores, that every match needs). Instead, there would be some modules like `ScoreMatchModule` that would just "always be there."

I do think about whether essential features like `Goal`s or scores should be part of the `Match` implementation. Ultimately, I think PGM needs a more robust concept of "scores / goals / victory conditions," likely combining those concepts somehow; but that's for something down the line.
