### ISSUE TITLE
Giving mined blocks directly into players inventory

### ISSUE THREAD

**Issue by RuedigerLP** [PGMDev/PGM#570]
This would make it possible to prevent iron block stealing and it would make a game possibly cleaner by reducing the items on the floor. It would be nice if items would be filtered somehow similar to how remove/keepitems and repairtools are done.

**Comment by Pugzy** [comment]
Can blockdrops be used for this purpose?

**Comment by Pablete1234** [comment]
I'm going to close this one because i'm pretty sure this is doable currently with blockdrops, give a kit of 1 iron block when someone mines an iron block, and drop nothing.
