### ISSUE TITLE
Control-Point ID error

### ISSUE THREAD

**Issue by RuedigerLP** [PGMDev/PGM#575]
if u have two hills that only have the capture-region attribute and no id or name attribute, the map will throw following error:
`The ID '--control-point--hill' is already in use by a different feature
`

**Comment by Pablete1234** [comment]
If you could provide a minimal XML that triggers this issue that'd help fixing it

**Comment by RuedigerLP** [comment]
https://www.dropbox.com/sh/mj9ro0wzs4jcn74/AACXls2vs0msFHBayXqKICbha?dl=0
