### ISSUE TITLE
Countdowns can have a negative durations

### ISSUE THREAD

**Issue by TiTo418** [PGMDev/PGM#613]
![aeadcf10fe8ab536c01eb0f44e0d9b8b](https://user-images.githubusercontent.com/67824022/90324687-3f3fb300-df48-11ea-9bae-7f2ba38e6cd0.png)

This happens when using /start without another argument

**Comment by Electroid** [comment]
Should disallow negative durations in any `Countdown` commands.

**Comment by Pablete1234** [comment]
@Electroid This is a configuration issue. You set start countdown in the config to -1 to disable autostart, that causes using `/start` with no argument to start with the default with the config, that being -1.
IMO the easy fix is to hard-code the duration provider with 30s start if it's < 0.
