### ISSUE TITLE
Re-format FFA scores in /match

### ISSUE THREAD

**Issue by applenick** [PGMDev/PGM#619]
Currently FFA scores under `/match` are formatted in a not so useful list:
![scores](https://user-images.githubusercontent.com/3377659/90484382-f07e4e80-e0ea-11ea-80ce-1dc05c143af7.png)

Would be nice to update the format to include a mix of usernames and scores. Ideally all participants should be displayed similar to `/list`, while sorting from highest to lowest score. 

An alternative simple fix would be to simply add a hover message with the player name over the scores. Though may not be that intuitive/useful for those who want a quick glance.

**Comment by mrcookieunderscore13** [comment]
I'll work on this issue. 😄
