### ISSUE TITLE
Control point name issue

### ISSUE THREAD

**Issue by applenick** [PGMDev/PGM#653]
# Control Point name issue

Just experienced this on OCC when using the latest commit.

Am fairly certain the cause of this error is from #650’s changes.

 I am going to be busy for a bit, otherwise I’d work on fixing this right now. If anyone is free and wants to take care of it, just let me know. Otherwise I’ll see if I can work on a fix later today or tomorrow. 

![error](https://user-images.githubusercontent.com/3377659/93655997-fca44700-f9db-11ea-8dfe-05d539f749c5.png)
 
Please make sure to always test your changes 😞

**Comment by Pablete1234** [comment]
https://github.com/PGMDev/PGM/commit/8c881301c4ada42843e6c697e0b486940ff8a929#r42455413

It was tested with the original issue, of hills without name, and then hills WITH names weren't tested
