### ISSUE TITLE
Investigate MySQL database lag

### ISSUE THREAD

**Issue by applenick** [PGMDev/PGM#684]
# More MySQL Database lag issues (High player count)
It’s been noticed recently on OCC that when player counts are upwards of 75-100+,  player settings (such as death messages) are incredibly slow to update/fetch, and in some cases don’t at all. 

I know this was originally address in #446, however it seems to still be an issue when a single PGM instance reaches a large player count. Small servers seem unaffected by this, as far as I have observed. 

If anyone has suggestions on how to investigate what could be causing the lag or possible solutions let me know. I’ll be happy to work on solving this if no one else does, when time allows.

**Comment by Electroid** [comment]
I wonder if [this](https://github.com/PGMDev/PGM/blob/dev/core/src/main/java/tc/oc/pgm/db/CacheDatastore.java#L35) is the culprit. Maybe it would work better to remove?

**Comment by applenick** [comment]
@Electroid 
Oh good point, that could indeed be the culprit! Want me to make a PR removing the line then test on OCC? 

Edit: I’ve removed that line & deployed the fix to OCC. I’ll report back after a day or so when more players are online to see if the issue persists or not.
