### ISSUE TITLE
/testmap (command suggestion)

### ISSUE THREAD

**Issue by technodono** [PGMDev/PGM#688]
this feature would allow for map creators to request to test a map by using this command:

/testmap [name_of_map]

The command however would only execute upon certain conditions:
- _The map would verify that the player-count on the server matches that of the map's team size + or - 10%_
- _The map request would then go to discord via cloudy (Discord bot) in a channel (accessible to staff only) and they could confirm/deny this request._

This would make it a lot easier for map creators to test their content and gain feedback rather than waiting for admins to go online and set it for them

**Comment by Pugzy** [comment]
Cloudy is OCC specific and not something implemented into PGM.

The idea is also pretty flawed as maps that are going through testing can often have breaking issues.
If the map was set from Discord (as suggested) nobody would be in-game to resolve any problems.

**Comment by applenick** [comment]
Agree with @Pugzy. This idea would only work if a few really specific conditions were met. Map creators are better off just requesting staff members to set their maps. If you are having trouble getting staff online to test, let me know and we can look into an OCC specific solution to solve that.  

I'm going to go ahead and close this issue, as it does fall outside of PGM's scope. 

Though please continue to suggest new ideas in the future 😄!
