### ISSUE TITLE
Incorrect color in tablist on death

### ISSUE THREAD

**Issue by Pablete1234** [PGMDev/PGM#692]
Dead players are supposed to be dark gray, at this time they're showing as light gray
Relevant code:

https://github.com/PGMDev/PGM/commit/7fdc210c34e1675e79d02bb18d834fc29323de92#diff-c1318b7f9d3e60e59ee45667d3a8fd44418ed5bee0c20ac6159179e9f5a13518R75

**Comment by applenick** [comment]
@Pablete1234 was it also intentional for vanished staff to have their names crossed out in the admin chat?
![Screen Shot 2020-11-05 at 5 11 34 PM](https://user-images.githubusercontent.com/3377659/98314062-20225180-1f8a-11eb-8bbe-91b9619dea8a.png)

**Comment by Pablete1234** [comment]
It is inteded behaviour that disguised names appear crossed out. Vanish is just one type of disguise

**Comment by applenick** [comment]
Thanks, just wanted to double check 👍
