### ISSUE TITLE
Reimplement "owner-points" for control points

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [PGMDev/PGM#716]
My idea for "flat-points" is for a control point to give out a set number of points when captured, instead of a linear amount of points like the default 1 point per second.
Control points can use a permanent module making it unable to be captured by another team once the control point is captured, and flat points might help make permanent control points more useful, though flat-points could also be used in hills that can be always captured.

I was thinking something like this for the XML. I'm going to take a try and this one.

```xml
<control-points capture-rule="lead" incremental="true" show-progress="true">
    <control-point name="Center" capture-time="20s" permanent="true" flat-points="20">
        <capture><cylinder base="0.5,23,7.5" radius="7" height="5"/></capture>
        <progress><cylinder base="0.5,22,7.5" radius="7" height="4"/></progress>
        <captured><cylinder base="0.5,64,7.5" radius="7" height="5"/></captured>
    </control-point>
</control-points>
```

**Comment by Pablete1234** [comment]
I added this feature myself to 1.9+ PGM, and should be reimplemented in the same way to support maps made at that time

It consisted of one `owner-points` attribute that would give that amount of points to the team if you owned that objective. Upon losing the objective you'd lose the points.
This allows for scoreboard displays where you just show team score, and the score is how many points you own at the time, and also allows style of maps where for example you need to own over half the points to win (each control point gives 1 score, there are 7 points and there's a score limit of 4)

Relevant original implementation:

https://github.com/OvercastNetwork/ProjectAres/blob/master/PGM/src/main/java/tc/oc/pgm/controlpoint/ControlPointParser.java#L94
https://github.com/OvercastNetwork/ProjectAres/blob/master/PGM/src/main/java/tc/oc/pgm/controlpoint/ControlPoint.java#L349-L353
