### ISSUE TITLE
Capture point visual-materials attribute doesn't function

### ISSUE THREAD

**Issue by CrazyisCreeps** [PGMDev/PGM#723]
It allowed you to filter which blocks would change when a hill was captured. Either the way it's applied no longer works, or support was removed. The filter is ignored, and all default blocks (wool, carpet, clay, glass, etc.) change even when otherwise specified 

Refer to https://github.com/CrazyisCreeps/maps.stratus.network/blob/master/other/tournament/conquest/cp/factori/map.xml#L72 for an example of the usage

**Comment by Pablete1234** [comment]
Seems like this version of PGM is only allows for that attribute to be named `visual-world`:
https://github.com/PGMDev/PGM/blob/dev/core/src/main/java/tc/oc/pgm/controlpoint/ControlPointParser.java#L53

While in 1.9+ PGM it was `visual-materials`:
https://github.com/OvercastNetwork/ProjectAres/blob/master/PGM/src/main/java/tc/oc/pgm/controlpoint/ControlPointParser.java#L63

From what i'm seeing in the commit history however, it seems like it was always `visual-materials`, so `visual-world` may be a typo made when open-sourcing, and should probably be removed in favor of `visual-materials`

**Comment by Electroid** [comment]
See ^
