### ISSUE TITLE
Observers can trigger block drop rules

### ISSUE THREAD

**Issue by CrazyisCreeps** [PGMDev/PGM#728]
In the specific example I tested, observers were able to trigger events related to the <trample> attribute of the block drops module. It should only allow participants to trigger this.

**Comment by CrazyisCreeps** [comment]
Also, this behaviour is relatively new. I'm testing it on my TNT-run like map, which hasn't been loaded on OCC for several months now. Prior to it being unloaded, this issue never occurred. I'm concerned that a recent commit is the culprit behind this, and it may be causing some other unintended issues.

**Comment by Pablete1234** [comment]
I remember modifying blockdrops because step was only triggered for people in adventure mode (people in survival couldn't trigger). Could be the cause

**Comment by CrazyisCreeps** [comment]
That makes sense logically

**Comment by Pablete1234** [comment]
For reference: https://github.com/PGMDev/PGM/commit/42d15a009e46d8ecba0ac434e254b5662df0ca8f

**Comment by Pablete1234** [comment]
@CrazyisCreeps Could you provide a minimal map for testing/debugging/fixing this issue?

**Comment by CrazyisCreeps** [comment]
https://mcresourcepile.github.io/maps/stratus?query=crazys_wool_run&match=all&invert=false

@Pablete1234
