### ISSUE TITLE
Translations with absent variables broken

### ISSUE THREAD

**Issue by Pugzy** [PGMDev/PGM#769]
Translations where variables are absent shift all existing variables down an index causing the message to break.

![image](https://user-images.githubusercontent.com/8608892/103476306-63434a00-4dac-11eb-8361-21425391e5c7.png)

The translation implementation changed so that variables previously passed as 0 (where no 0 exists in the string) get shifted a position along, `0 -> 1`, `1 -> 2`, `2 -> 3`.

Not sure how many translations this will affect but I did notice this on the destroyable touch messages.

```properties
# {0} = player name
# {1} = monument name
# {2} = team name
destroyable.touch.owned.player = {2}''s {1} damaged by {0}
destroyable.touch.owned.you = You damaged {2}''s {1}
destroyable.touch.owned = {2}''s {1} has been damaged
```

In the above messages, you can see how the last two do not contain a `{0}` variable. FYou can see that the first var (0) is the player's name which does not appear in those messages but does in the first one. 

The code would previously compensate for this by passing `empty()` as a translatable argument.

https://github.com/PGMDev/PGM/blob/c42de5bbb018549167a277d67d7dd4a7ed091f63/core/src/main/java/tc/oc/pgm/core/Core.java#L114

The translate implementation should be updated to work in this previously expected way OR translations files and code like the above should be updated removing the empty variables (not sure how many exist or how hard each of these options would be).

**Comment by Electroid** [comment]
This is an `adventure` bug that was fixed, will be released in `4.4.0`: https://github.com/KyoriPowered/adventure/pull/252
