### ISSUE TITLE
Consider flags for determining the winner of CTF/Blitz maps

### ISSUE THREAD

**Issue by OhPointFive** [PGMDev/PGM#770]
I have the following XML (with irrelevant details cut out):

```xml
<blitz>
    <lives>1</lives>
</blitz>
<score>
    <kills>0</kills>
    <deaths>0</deaths>
    <limit>1</limit>
</score>
<flags>
    <flag>
        <net points="1"/>
    </flag>
</flags>
```

When someone captures a flag, the winner is whichever team has more players, _not_ whichever team capped the flag.

---

We discussed this [for a bit in discord](https://discord.com/channels/730855489767997511/730860066261172394/795146784619364404).

Notably, Pablo said:
> currently there's a disconnect between what ends the match and who gets winner
> they're handled separately, they shouldn't be

**Comment by Pablete1234** [comment]
To add more context to this, what currently happens is blitz takes priority over scores or objectives, so if you cap all wools (complete objectives) or reach score max (by capping flags, scoreboxes or whatever) the match ends, but the winner is determined first by what team has the most players alive.
