### ISSUE TITLE
Double-jump but as an item

### ISSUE THREAD

**Issue by lefckntea** [PGMDev/PGM#801]
pressing space twice is a stupid mechanic. right clicking an item is way cooler
make it so i can give a tag (or however this works) to a specific item (for example in a kit) so i can leap with it.

**Comment by Pablete1234** [comment]
i don't think pressing space twice for double-jumping is "a stupid mechanic", but that doesn't mean we can't support both

**Comment by cswhite2000** [comment]
Effectively resolved by https://github.com/PGMDev/PGM/pull/1348 and https://github.com/PGMDev/PGM/pull/1346
