### ISSUE TITLE
New gamemode: CP: Capture Point 

### ISSUE THREAD

**Issue by lefckntea** [PGMDev/PGM#802]
CP: Capture Point

idk if it's already possible in pgm but it's basically a brand new gamemode
it has a capture hill in the middle, both teams fight for it. you can't respawn. if one team captures it (most likely after killing all the enemies) you get 1 point. then everyone respawns at the same time again until a point limit is reached
for comp 7v7 could be cool not sure about public 20v20s 

you might think: "Complex CP is already pretty similiar, no?" yes, but it's not rounds. making more maps like complex cp in the comp scene would essentially just be 5cp without pushing to 2nd. one team holds mid and it occasionally swaps. but it's generally really stale and is determined by getting people low or dead with bow. the team pushing is always at a disadvantage or you give them positional advantage but then it's not balanced either. and 5cp is already the worst gamemode of conquest. so no respawning and then everyone goes at the same time is better, it's balanced.

**Comment by Pablete1234** [comment]
This isn't a feature request for PGM, since PGM is already able to support most of this with spawn filters, the only required extra thing would be a way to decay an already captured filter, but you should make a separate issue for that
