### ISSUE TITLE
Reimplement decay, recovery, and allow decay from captured state on control points

### ISSUE THREAD

**Issue by lefckntea** [PGMDev/PGM#803]
![image](https://user-images.githubusercontent.com/39029307/107823561-525cff80-6d80-11eb-9675-e90f587e7884.png)
make it so capture points have those

**Comment by Pablete1234** [comment]
1.9+ PGM had `decay` and `recovery` attributes added, which handled how quick points uncaptured or re-captured, replacing incremental (which simply resets progress to 0% if set to false, or doesn't change progress at all if set to true), additionally, it'd be nice to have a new flag for a point uncapturing on its own (if no one is standing on it) which was the original feature-request when decay & recovery were implemented, but got lost in the way

**Comment by lefckntea** [comment]
*Also a way to have decay from captured state but not decay from an uncaptured state. So your progress while capturing a point stays but it can then automatically uncapture from the capture state

**Comment by Pablete1234** [comment]
Then the proposal would be `decay`, `recovery` and `owned-decay`, which defaults to infinity. 
`decay` applies when it's not owned and partially captured and no one stands on it (or only non-capturing competitors are on it)
`recovery` applies when it's owned and partially uncaptured, but the capturers all left (eg: no one on it anymore)
`owned-decay` applies when it's owned, and owning competitor isn't on it.

recovery and owned-decay are mutually exclusive as one is ticking up and the other ticking down, while owned
