### ISSUE TITLE
Players entering their own wool rooms by sneaking

### ISSUE THREAD

**Issue by drmzio** [PGMDev/PGM#812]
## Describe the bug
Players are able to "enter" their own wool rooms by sneaking at the very edge of the wool room platforms. This is only specific to some maps where the wool rooms are not entirely covered by bedrock, such as Golden Drought or Race for Victory 2, where players can walk around the wool room platform.

## To Reproduce
1. Go to your own team's wool room
2. At the very edge of either side, use sneak
3. Proceed into the wool room platform from the very edge
4. Do not get any closer to the wool room itself or it will knock you off "You cannot enter your own wool" message or something like that.

## Expected behavior
Server should knock you back with a "You cannot enter your own wool room" message or similar.

## Screenshots
**No screenshots yet**

## Client Information (please complete the following information)
 - **Minecraft Version**: 1.16.5

**Comment by Pablete1234** [comment]
This is not an issue in PGM, the regions simply do not extend to the void
