### ISSUE TITLE
Ready countdown no longer uses seconds

### ISSUE THREAD

**Issue by Pablete1234** [PGMDev/PGM#813]
![image](https://user-images.githubusercontent.com/11789291/108148814-e2c57800-70d1-11eb-94b1-7388b89aeb99.png)

This is a bit weird to see, should probably not be using this format

**Comment by Electroid** [comment]
Fixed in https://github.com/PGMDev/PGM/commit/bd78bb35d4bcea04dc5be3e9b8d1d495ef5aba16
