### ISSUE TITLE
Damage dealt is not limited to max health

### ISSUE THREAD

**Issue by Pablete1234** [PGMDev/PGM#817]
![image](https://user-images.githubusercontent.com/11789291/108620927-b4c49880-742f-11eb-81ca-f321b25b0952.png)

In a blitz match, a single kill got 1K damage, the stats for damage calculation should be limited to the enemy players' health, if you deal 5 hearts of damage to someone who had 2 hearts left, it should only count 2 hearts of damage, not 5

**Comment by Pugzy** [comment]
Can be closed. Fixed in the above commit.
