### ISSUE TITLE
Block Drop's trample attribute no longer works

### ISSUE THREAD

**Issue by CrazyisCreeps** [PGMDev/PGM#835]
I brought it up in the OCC mapdev discord channel but I wanted to make sure it won't be forgotten and open up an issue. As of right now, it doesn't appear that the trample attribute is getting triggered. I suspect it's related to the last change made that affected this attribute, where observers were able to trigger events (https://github.com/PGMDev/PGM/pull/795)

**Comment by Pablete1234** [comment]
I think the issue of them not working is probably related to what was fixed in #1086 
Feel free to re-open if you can still replicate the issue, try to include a map where this happens if that's the case
