### ISSUE TITLE
Possible crash in text parser

### ISSUE THREAD

**Issue by chidddy** [PGMDev/PGM#838]
during the config loading you can cause a crash with anything that uses `ParseComponent` or `ParseLegacyComponent` (MOTD, sidebar, tablist, flair) if it is something like (using MOTD as an example) `{0}\n {2}> {1}` 

because they both reach here
https://github.com/PGMDev/PGM/blob/4038dae5e314c0c964a0d8c705d8e408385cbeba/util/src/main/java/tc/oc/pgm/util/text/TextParser.java#L382-L388

and trigger attempting to parse it all as GSON because it fits the startswith and endswith condition.

**Comment by Electroid** [comment]
Closed in c7409fcdd060c367848c4d20160633f259f86374
