### ISSUE TITLE
Implement a separate "King of the Flag" gamemode

### ISSUE THREAD

**Issue by calcastor** [PGMDev/PGM#876]
Currently, PGM deems all maps which implement flags as "Capture the Flag" maps. As a result, maps such as Desert Sanctuary by Strangey and Avaleer and Maple Syrup by Xerocoles and Zaquez, where the goal is for your team to control the flag for the longest, are grouped, by default, as "Capture the Flag" maps, despite having distinctly different gameplay. In the `/map` info for these maps, they will also default appear with the `#flag` tag; while not incorrect this too does not differentiate between the differences in gameplay.

The current workaround for this, at least cosmetically, is to specify the game title for these maps with the `<game>` module or as a specified attribute of the `<map>` module. At least colloquially (and in PGM's documentation), maps with this play style tend to be referred to as "King of the Flag" maps, and defining them as such with the aforementioned module or attribute will change the title of the scoreboard during the match. However, this has a few limitations:

1. A custom gamemode title specified with `<game>` or within `<map>` is hard coded and thus overrides any translations for game mode titles.
2. Maps defined in this manner will continue to be grouped together with typical "Capture the Flag" maps, under the tag `#flag` , despite their gameplay differences.
3. Perhaps least of all, it's just inconvenient.

In my opinion, the best solutions for this are as follows (provided such solutions are feasible):

1. Add a separate "King of the Flag" gamemode, that can be defined with the module `<gamemode>kotf</gamemode>` if needed. Ideally, this should happen automatically as tends to be the case with most gamemodes.. Maps where this gamemode should be automatically identified are those in which a team gains points at a specified rate only while a member of that team is holding the flag.
2. Rename or the current `#flag` tag which appears in `/map` to `#ctf`, and add a separate `#kotf` tag.

**Comment by CoWinkKeyDinkInc** [comment]
A custom and translatable gamemode title can be quickly addressed with PR #873

**Comment by CoWinkKeyDinkInc** [comment]
This feature is now implemented.
