### ISSUE TITLE
Kill Kit

### ISSUE THREAD

**Issue by RuedigerLP** [PGMDev/PGM#880]
A kit that kills the palyer it gets applied to.
`<kill/>` maybe with an silent attribute to make the kill not count towards stats.

**Comment by Pablete1234** [comment]
Did you try to set players' health to 0, or set their health to 1 and give them instant damage?

**Comment by Pablete1234** [comment]
Seeing the lack of response and that i don't see this being any different to what's already possible, i'm going to close this.

Feel free to open a new issue with more detailed information or explain on discord what the use-case you need is so we can sort out what actual feature pgm would need to support the use-case

**Comment by Pugzy** [comment]
You can kill people with damage potion effects. To kill a person without any of the killing would that not just be a respawn?

Would a force respawn kit with or without the countdown be of use (or possible) for this scenerio.

```xml
<kit id="respawn">
    <respawn countdown="10s"/> <!-- maybe 0 for no cooldown? -->
</kit>
```
