### ISSUE TITLE
Extinguishing fires while in observer

### ISSUE THREAD

**Issue by destial** [PGMDev/PGM#884]
You can extinguish fires in the map while in observer mode.

![destroy_fire](https://user-images.githubusercontent.com/67675805/120573280-e3e79e80-c44f-11eb-82a8-9f7181d5c620.gif)

Recreation:
- Cycle to a map that has fire
- Left click on fire

**Comment by Pablete1234** [comment]
Are you sure this is not just a client-side desync? try right-clicking after extinguishing, or looking at it from another players' prespective

**Comment by destial** [comment]
Oh it is client side, my bad. Thanks for the reply.

**Comment by CoWinkKeyDinkInc** [comment]
This is a really old bug, but as it stands it doesn't really do anything

**Comment by CoWinkKeyDinkInc** [comment]
This has been a bug present in PGM for years, but yes, the fire is only a client side effect and otherwise doesn't change anything.
