### ISSUE TITLE
Connection reset

### ISSUE THREAD

**Issue by ghost** [PGMDev/PGM#889]
This is a bit confusing, but I can't get into the server where I have the pgm, I get "connection reset by peer" "broken pipe" etc.

I've been trying changing the server.properties or sportpaper.yml config, thinking it was something I changed, but still nothing, this is just happening to me.

Now I tried removing all the plugins I could enter, then I tried removing plugin by plugin and when I removed pgm, it let me enter the server without disconnection, do you know why that happened, just today out of the blue it happened to me.

When I have the normal pgm installed and I try to log in, nothing loads, the tablist appears empty, etc.

I am using the latest version of PGM, and version 36 of sportpaper, because with 38 and 39, it drops all players for invalid packets, when it is a TNT game because of the explosions.

The version 37 of sportpaper I don't know if it happens the same on the "invalid packets", but in the last two versions I tested them and if it happens the same, but with the 36 it is normal.

**Comment by Pablete1234** [comment]
This looks more of a sysadmin issue than a PGM one, the help channel of discord will be of more help than this
