### ISSUE TITLE
Match stats longest shot seems inaccurate 

### ISSUE THREAD

**Issue by brendanfuller** [PGMDev/PGM#892]
I've recently noticed that end game **match stats** only care about about the longest shots/sniped shots on land rather than shots that have death by void, or death by falling. All I'm wondering is should all bow shots count and not just land shots, assuming this is not intended. 

Originally I thought it was due to the 60 block sniped vs shot but that doesn't seem to be the issue.

Though anyways here some evidence: 
1. I kill someone with a great shot (these images are all from the same match)
![Screenshot_20210622_133124](https://user-images.githubusercontent.com/13824197/123019176-f8a7ba00-d39d-11eb-9900-176bf9a65a94.png)
2. The match ends, but its only the attacker who had the land shot (which is rounded up for some reason?)
![Screenshot_20210622_133113](https://user-images.githubusercontent.com/13824197/123019163-f2194280-d39d-11eb-8ef5-7a6f0dbfc4c1.png)
3. Find said attacker, who got that "longest shot" in the chat, which was on land
![Screenshot_20210622_133140](https://user-images.githubusercontent.com/13824197/123019172-f5143300-d39d-11eb-9b1f-0824783ef3ec.png)

Further more I wanted to see if this was common with every match I've played/spectated via the Minecraft logs.
So I create a simple python script to see said information:

Out of **432** games which have the Match Stats shown, only **112** of them were actually accurate, and **106** of them were all land shots only. 

For anyone interested here's the the outputted data from said python script here ya go [matches.txt](https://gist.github.com/ImportProgram/8d429c3ed5fe0eb4f01ae57245133394)

**Comment by KingOfSquares** [comment]
Oh yeah thats not intended but its something i never found the reason for when i initially made it.

**Comment by Pugzy** [comment]
I though the falling/void deaths included the distance the person fell too? This would make them inaccurate as the arrow doesn't actually hit at that range.

**Comment by Pablete1234** [comment]
Match stats is what is accurate, it's the distance the arrow traveled, kill message however, is distance from killer to victim at their time of death, so if you knock them out of the world all the height they fall is added up

**Comment by CoWinkKeyDinkInc** [comment]
Fixed

**Comment by Pablete1234** [comment]
> Fixed

Could you reference the commit/pr that fixed it? If you mean #897 it only fixed one (small) issue, but not the big difference

**Comment by Pugzy** [comment]
> Could you reference the commit/pr that fixed it? If you mean #897 it only fixed one (small) issue, but not the big difference

Unless scenarios like 'sniped out of the world' are updated to only be the distance the arrow flew I don't think they should be considered longest shots.

**Comment by Pablete1234** [comment]
> Unless scenarios like 'sniped out of the world' are updated to only be the distance the arrow flew I don't think they should be considered longest shots.

Yeah, the fix is to modify the sniped out of the world message to only include how long your snipe was, not how far they fell after you sniped them. Should be distance between shooting point and impact on the attacker, like match stats are properly reporting

**Comment by Pugzy** [comment]
The changes made in https://github.com/PGMDev/PGM/pull/897 and https://github.com/PGMDev/PGM/pull/1272 should both resolve this discrepency.
