### ISSUE TITLE
Message Kit

### ISSUE THREAD

**Issue by RuedigerLP** [PGMDev/PGM#900]
A kit component that displays a message either in chat, as a title/sub-title or above the hotbar, for the player that recieves the kit. I think it could be rly useful to alert palyers especially to kits that dont directly go into the hotbar like armor or potion effects. Maybe it would also be useful to have the possibility to play a sound effect with the message maybe as a Sound Kit.

**Comment by CoWinkKeyDinkInc** [comment]
Tips and alerts can already be triggered by filter events, so this is already possible. This would still be a good addition.

**Comment by CoWinkKeyDinkInc** [comment]
Messages can already be triggered by filter events, so this is already possible. This would still be a good addition.

**Comment by Pugzy** [comment]
One issue would be that just like the other text-based XML stuff (region deny messages, tips/alerts) they wouldn't be translatable so if relaying key information could be tricky for non-native English players to understand what's happening.

**Comment by RuedigerLP** [comment]
https://github.com/PGMDev/PGM/pull/1016
