### ISSUE TITLE
Inside Apply Element

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [PGMDev/PGM#906]
PGM should have a new apply element that triggers when players are *inside* a region. Currently what is supported are trigger events when players enter or leave a region, making more dynamic filters and events using `<time>`, `<objective>`, `<kill-streak>`, etc, harder to implement. If a player is inside a region before the filter meets the criteria, it does not apply to them. So the current workaround is to make a grid of regions spaced apart so a player will "walk into" it. 

### Example: 
```xml
<apply region="region1" inside="green-filter"/>
```

**Comment by Pablete1234** [comment]
I have a few issues with this:
  - The `inside` keyword has little to nothing to relate with kits, it would be extremely misleading
  - There's no way to give a kit when leaving a region (you can, however, give it when entering the negative of the region)
  - What you're requesting, is essentially the same as `lend-kit`. It however has a few limitations as to what kits are removable
  - The whole request just depends on dynamic filters which do not exist in this version of pgm yet
  - PGM 1.9+ had give, take and lend dynamic filters directly on the kit, regions can be used as a filter (it filters position)

**Comment by CoWinkKeyDinkInc** [comment]
I meant to say "green-kit-filter" or something, what would be placed in `inside=` is a reference to a filter. It doesn't have to involve kits.

**Comment by Pablete1234** [comment]
> I meant to say "green-kit-filter" or something, what would be placed in `inside=` is a reference to a filter. It doesn't have to involve kits.

Kits already have a filter property, what exactly does inside apply to? enter, leave etc all have filters as parameter already

**Comment by CoWinkKeyDinkInc** [comment]
inside would be a trigger event in the same way as enter, leave, block, block-place, block-place-against, block-break and use.

**Comment by Pablete1234** [comment]
> inside would be a trigger event in the same way as enter, leave, block, block-place, block-place-against, block-break and use.

enter, leave, and all the others already have their triggers (eg: when entering, or placing blocks). What does `inside` bring to them? does it affect them at all?

**Comment by CoWinkKeyDinkInc** [comment]
Dynamic filters does what I struggled to explain here.
