### ISSUE TITLE
Color codes get ignored after line break for tips and alerts

### ISSUE THREAD

**Issue by RuedigerLP** [PGMDev/PGM#907]
so after a line break the text formattion goes to italic light aqua (default)

**Comment by master00ofdsiware** [comment]
It's a 1.8 client side bug if I understand it correctly. 1.16 users see the text properly.

**Comment by RuedigerLP** [comment]
But what I don't understand, if it's a vanilla bug why isn't the text reset to white non-italic, but to light aqua italic.

**Comment by Pablete1234** [comment]
It's a result of mixing in text components and formatting color codes

Color codes do not carry over line-breaks client-side, and it resets to whatever color the text-component was (usually to white)

**Comment by KingOfSquares** [comment]
Was this not fixed in https://github.com/PGMDev/PGM/pull/947?
