### ISSUE TITLE
Broadcast module does not work after map is reloaded

### ISSUE THREAD

**Issue by Jaaquinn** [PGMDev/PGM#938]
The "rules" and "broadcasts" do not work when I put the same map again, that is, the ads come out for the first time but if I write / sn Xmap and put the same map as before, the ads don't work or appear, just when I reset the server they appear again, but the bug is repeated. The PGM plugin I use is the Spanish translation.

**Comment by Pablete1234** [comment]
Please provide an example map or xml for debugging

**Comment by Jaaquinn** [comment]
https://paste.gg/p/anonymous/de3f74be2f1d408298449aa74fea0c94

This happens if it is a map of the resourcepile or when creating a map, here an example of the "Bewitched" map

**Comment by Jaaquinn** [comment]
Well, a moment ago I have been testing this again and if I let the game end and cycle another map, and then I put the previous map back if the ads appear. But it is somewhat ambiguous because when giving /finish or just placing the wools to end the game and after a while I put the same map, the ads don't work. I don't know if you can prove this to see if it happens to you.

**Comment by CoWinkKeyDinkInc** [comment]
Yep, this doesn't work on my testmap either after using `/recycle`. The title should be changed to "Broadcast module does not work after map is reloaded".

**Comment by CoWinkKeyDinkInc** [comment]
Is there a reason that `unload()` is used in BroadcastMatchModule? I seen that `unload()` is uncommon, this might be our issue here since broadcasts will return empty when I was debugging.
