### ISSUE TITLE
Reimplement friendly-fire

### ISSUE THREAD

**Issue by lefckntea** [PGMDev/PGM#954]
It's documented but not implemented in current 1.8 pgm

pretty sure everyone knows what friendly fire means

i wanna use it so i can make boosting be a thing on 5v5 comp maps like it was on badlion

**Comment by Pablete1234** [comment]
Reference for what i told mame:
https://github.com/PGMDev/PGM/blob/dev/core/src/main/java/tc/oc/pgm/scoreboard/ScoreboardMatchModule.java#L82

In old pgm:
https://github.com/OvercastNetwork/ProjectAres/blob/master/PGM/src/main/java/tc/oc/pgm/scoreboard/ScoreboardMatchModule.java#L88

https://github.com/OvercastNetwork/ProjectAres/search?q=friendlyfire

**Comment by CoWinkKeyDinkInc** [comment]
> upvote for a chance to win a new iPhone 13 pro max (real)

upvoted

**Comment by lefckntea** [comment]
next to my initial way i wanted to utilize friendly fire (boosting team mates) i made another map which would greatly benefit from friendly fire.
custom projectiles can apply an effect to another player when hit. but this only works if you damage the other player with your projectile

with friendly fire i could make like a regeneration snowball gun or whatever projectile and hit my team mate with it. without friendly fire the only way i can apply an effect to my team mate with a custom projectile is primedtnt i think

**Comment by KingOfSquares** [comment]
Can be closed now because of #981 ?
