### ISSUE TITLE
Blitz FFAs allowing players to join midgame

### ISSUE THREAD

**Issue by Xerocoles** [PGMDev/PGM#961]
In Blitz FFA (not team blitz, but specifically only ffa blitz) you can join from observers into the active players midgame, which absolutely ruins lots of maps of course

I tested on both Stratus and OCC, on multiple maps, it always seems to be blitz ffas in particular

**Comment by calcastor** [comment]
tested this on OCC/BOLT private servers (which are running 3d28b3b0c5fb68d944c59a2c8669ffd7fd5282a8) on the map Flappy Bird (blitz FFA arcade map). wondering if #945 is affecting it?

**Comment by CoWinkKeyDinkInc** [comment]
I think it's more related to #960 .

**Comment by calcastor** [comment]
> I think it's more related to #960 .

that was my initial thought, however the Stratus fork this was tested on has #945 but not #960 to my knowledge. the Stratus fork this was tested on has a different change to fix what #960 solved.

edit: the aforementioned change (won't apply upstream as it applies onto a previous version of #951) 

```diff --git a/core/src/main/java/tc/oc/pgm/stats/StatsMatchModule.java b/core/src/main/java/tc/oc/pgm/stats/StatsMatchModule.java
index 6114b1f6..6e3b97fd 100644
--- a/core/src/main/java/tc/oc/pgm/stats/StatsMatchModule.java
+++ b/core/src/main/java/tc/oc/pgm/stats/StatsMatchModule.java
@@ -103,8 +103,10 @@ public class StatsMatchModule implements MatchModule, Listener {
         Math.min(event.getFinalDamage(), ((Player) event.getEntity()).getHealth())
             + absorptionHearts;
 
-    if (damager != null) getPlayerStat(damager).onDamage(realFinalDamage, bow);
-    if (damaged != null) getPlayerStat(damaged).onDamaged(realFinalDamage, bow);
+    if (damager != null) {
+      getPlayerStat(damager).onDamage(realFinalDamage, bow);
+      getPlayerStat(damaged).onDamaged(realFinalDamage, bow);
+    }
   }
 
   @EventHandler```

**Comment by Pablete1234** [comment]
The regression is caused by 5cd0197, 

https://github.com/PGMDev/PGM/commit/5cd0197c816a6638615a68c37a70d4ad9fd6d9a4#diff-7a44dedefcea2791290af6b24d7cc76eb9dff89f21bff531b56551ad57e35ecaR98 
The non-null check will always be false on non-team-based maps (ffa). This was done to fix not being able to `/team force` players into the match, easiest fix is to simply change `(tmm != null && !tmm.isForced(player))` with `(tmm == null || !tmm.isForced(player))`

**Comment by Electroid** [comment]
Mind taking a look @applenick?
