### ISSUE TITLE
Map author asterisk disappears after consecutive map

### ISSUE THREAD

**Issue by rockymine** [PGMDev/PGM#963]
![](https://cdn.discordapp.com/attachments/880502054722887723/938880595201773578/2022-02-03_20.34.46.png)

**Description of the issue**
I am the author of many maps on the PGM server. Since they happen to be in the pools and people vote for them, it often happens that several of my maps are played one after the other. When I am online, the map author asterisk is displayed for these maps, but always only for the first map when two maps are played in succession.

**How to replicate this issue?**
Be the author of too many maps.

The above image shows (or well it does not) the missing asterisk on the map Townside. In the previous match, Outback was played. Below is a screenshot of the corresponding [match-status messages of Cloudy.](https://discord.com/channels/86514356862320640/792850275185721415/938874804054917240) 

![](https://imgur.com/GnGQ42u.png)

**Comment by Pablete1234** [comment]
This was fixed in #1145
