### ISSUE TITLE
Maps set next are ignored when pools disabled

### ISSUE THREAD

**Issue by calcastor** [PGMDev/PGM#970]
While #966 fixed an issue with set next maps being set twice, the change makes it impossible to cycle to a set next map or force-cycle to a specific map when pools are disabled.

How to replicate:

1. Configure a server with PGM, but disable pools in the PGM config
2. Ingame, use `/sn` to set a map, or use `/cycle` to cycle to a specific map. When cycling, a random map will be loaded.

If you have access to `/server mapdev` on OCC, this can be observed there as its PGM build has this commit, and pools are disabled in its config.

**Comment by alexsosnovsky** [comment]
I'll get on this.

**Comment by calcastor** [comment]
Closed with #979
